---
- name: installing apache2 server
  hosts: webserver
  become: true
  gather_facts: false
  tasks:
  - name: installing packages
    apt:
      name: apache2
      state: latest
  - name: start apache server
    service:
      name: apache2
      state: started
      enabled: true
  - name: deploy static website
    copy:
      src: index.html
      dest: /var/www/html/
...
      
    
